extra_hosts:
    - "host.docker.internal:host-gateway"

include:
  - ./auth-service.yaml
  - ./nginx.yaml
  - ./recipe-service.yaml
  - ./database-api-wrapper.yaml
  - ./swagger-ui.yaml
  - ./meal-service.yaml
